FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04
FROM ubuntu:20.04

###
# Set Python
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

###
# Install OS Package
RUN apt-get update && \
    apt-get install -y python3.9 python3.9-dev python3-pip python3-setuptools && \
    pip3 --no-cache-dir install --upgrade pip && \
    pip3 --no-cache-dir install Cython && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    apt-get install -y libaio1 unixodbc unixodbc-dev vim gcc wget unzip wget nginx ca-certificates && \
    apt-get install -y make libz-dev libssl-dev libffi-dev openssl && \
    rm -rf /var/lib/apt/lists/*

###
# Install Python 3.9

RUN mkdir -p /tmp
WORKDIR /tmp

RUN wget https://www.python.org/ftp/python/3.9.16/Python-3.9.16.tgz && \
    tar xzvf Python-3.9.16.tgz  && \
    cd Python-3.9.16 && \
    ./configure --with-ssl && \
    #make && \
    #make install && \
    make altinstall && \
    cd .. && rm -rf Python-3.9.16

RUN rm -rf /usr/bin/python && \
    rm -rf /usr/bin/python3 && \
    ln -s /usr/local/bin/python3.9 /usr/bin/python && \
    ln -s /usr/local/bin/python3.9 /usr/bin/python3

###
# PIP
#RUN wget https://bootstrap.pypa.io/get-pip.py
#RUN python get-pip.py
RUN python -m pip install --user --upgrade pip


WORKDIR /


###
# CUDNN
ENV NV_CUDNN_VERSION 8.2.4.15
#ENV NV_CUDNN_VERSION 8.2.4.12
#ENV NV_CUDNN_VERSION 8.3.2.44
ENV NV_CUDNN_PACKAGE "libcudnn8=$NV_CUDNN_VERSION-1+cuda11.4"
ENV NV_CUDNN_PACKAGE_DEV "libcudnn8-dev=$NV_CUDNN_VERSION-1+cuda11.4"
ENV NV_CUDNN_PACKAGE_NAME "libcudnn8"

###
# Install OS Package
RUN apt-get install -y --no-install-recommends ${NV_CUDNN_PACKAGE} ${NV_CUDNN_PACKAGE_DEV} && \
    apt-mark hold ${NV_CUDNN_PACKAGE_NAME} && \
    rm -rf /var/lib/apt/lists/*

###
# Install Python Package
#RUN pip install --index-url=http://10.81.121.104:13086/simple/ --trusted-host 10.81.121.104 -r /requirements.txt && \

COPY requirements.txt /
RUN pip install -r /requirements.txt && \
    rm -rf /requirements.txt


###
# TimeZone
ENV TZ=Asia/Seoul
RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime


###
# PIP
#RUN mkdir -p /root/.pip
#COPY pip.conf /root/.pip/


###
# EntryPoint
#ENTRYPOINT ["python3", "/app/python_version.py"]


